{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rabbitmq-cluster-operator-rolebinding
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbitmq-cluster-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rabbitmq-cluster-operator.serviceAccountName" . }}
    namespace: {{ include "rabbitmq-cluster-operator.namespace" . }}
{{- end }}

